# .github/workflows/main.yml

name: Test & Build

on:
  workflow_call:
  push:
    branches:
    - main
    - release/*
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version-file: ./go.mod
    - run: make test
    - uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Go Test Results
        path: .test/reports/**-test.xml
        reporter: java-junit
        fail-on-error: 'true'
    - uses: actions/upload-artifact@v3
      if: success() || failure()
      with:
        name: Test Reports
        path: .test/reports/**

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: ./go.mod
          check-latest: true
      - run: make lint
